apiVersion: v1
kind: Deployment
metadata:
  name: mean-booster
spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
